name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Create Xcode Project
      run: |
        mkdir ExodusWallet
        cd ExodusWallet
        
        # Create project structure
        mkdir -p ExodusWallet.xcodeproj
        mkdir -p ExodusWallet
        
        # Create project.pbxproj
        cat > ExodusWallet.xcodeproj/project.pbxproj << 'EOF'
        // !$*UTF8*$!
        {
          archiveVersion = 1;
          classes = {
          };
          objectVersion = 56;
          objects = {
            1B2E3F4D2A1B2C3D4E5F6789 /* ExodusWalletApp.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ExodusWalletApp.swift; sourceTree = "<group>"; };
            1B2E3F4E2A1B2C3D4E5F678A /* ContentView.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ContentView.swift; sourceTree = "<group>"; };
            1B2E3F502A1B2C3D4E5F678C /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = "<group>"; };
            1B2E3F532A1B2C3D4E5F678F /* Preview Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = "Preview Assets.xcassets"; sourceTree = "<group>"; };
            1B2E3F4A2A1B2C3D4E5F6786 /* ExodusWallet.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = ExodusWallet.app; sourceTree = BUILT_PRODUCTS_DIR; };
            1B2E3F492A1B2C3D4E5F6785 /* ExodusWallet */ = {isa = PBXGroup; children = (1B2E3F4D2A1B2C3D4E5F6789 /* ExodusWalletApp.swift */, 1B2E3F4E2A1B2C3D4E5F678A /* ContentView.swift */, 1B2E3F502A1B2C3D4E5F678C /* Assets.xcassets */, 1B2E3F522A1B2C3D4E5F678E /* Preview Content */,); name = ExodusWallet; sourceTree = "<group>"; };
            1B2E3F522A1B2C3D4E5F678E /* Preview Content */ = {isa = PBXGroup; children = (1B2E3F532A1B2C3D4E5F678F /* Preview Assets.xcassets */,); path = "Preview Content"; sourceTree = "<group>"; };
            1B2E3F482A1B2C3D4E5F6784 /* Products */ = {isa = PBXGroup; children = (1B2E3F4A2A1B2C3D4E5F6786 /* ExodusWallet.app */,); name = Products; sourceTree = "<group>"; };
            1B2E3F472A1B2C3D4E5F6783 = {isa = PBXGroup; children = (1B2E3F492A1B2C3D4E5F6785 /* ExodusWallet */, 1B2E3F482A1B2C3D4E5F6784 /* Products */,); sourceTree = "<group>"; };
            1B2E3F5A2A1B2C3D4E5F6796 /* PBXNativeTarget */ = {isa = PBXNativeTarget; buildConfigurationList = 1B2E3F572A1B2C3D4E5F6793 /* XCConfigurationList */; buildPhases = (1B2E3F472A1B2C3D4E5F6784 /* Sources */, 1B2E3F482A1B2C3D4E5F6785 /* Frameworks */, 1B2E3F492A1B2C3D4E5F6786 /* Resources */,); buildRules = (); dependencies = (); name = ExodusWallet; productName = ExodusWallet; productReference = 1B2E3F4A2A1B2C3D4E5F6786 /* ExodusWallet.app */; productType = "com.apple.product-type.application"; };
          };
          rootObject = 1B2E3F472A1B2C3D4E5F6783 /* Project object */;
        }
        EOF
        
        # Create App file
        cat > ExodusWallet/ExodusWalletApp.swift << 'EOF'
        import SwiftUI

        @main
        struct ExodusWalletApp: App {
            var body: some Scene {
                WindowGroup {
                    ContentView()
                }
            }
        }
        EOF
        
        # Copy the main content
        cp ../ContentView.swift ExodusWallet/ContentView.swift
        
        # Create Assets
        mkdir -p ExodusWallet/Assets.xcassets
        mkdir -p ExodusWallet/Assets.xcassets/AppIcon.appiconset
        mkdir -p ExodusWallet/Assets.xcassets/AccentColor.colorset
        mkdir -p "ExodusWallet/Preview Content"
        mkdir -p "ExodusWallet/Preview Content/Preview Assets.xcassets"
        
        # Create minimal asset files
        echo '{"images":[{"idiom":"universal","platform":"ios","size":"1024x1024"}],"info":{"author":"xcode","version":1}}' > ExodusWallet/Assets.xcassets/AppIcon.appiconset/Contents.json
        echo '{"info":{"author":"xcode","version":1}}' > ExodusWallet/Assets.xcassets/Contents.json
        echo '{"colors":[{"color":{"color-space":"srgb","components":{"alpha":"1.000","blue":"0.878","green":"0.463","red":"0.624"}},"idiom":"universal"}],"info":{"author":"xcode","version":1}}' > ExodusWallet/Assets.xcassets/AccentColor.colorset/Contents.json
        echo '{"info":{"author":"xcode","version":1}}' > "ExodusWallet/Preview Content/Preview Assets.xcassets/Contents.json"
    
    - name: Build Project
      run: |
        cd ExodusWallet
        xcodebuild -project ExodusWallet.xcodeproj -scheme ExodusWallet -configuration Release -destination 'generic/platform=iOS' -archivePath ExodusWallet.xcarchive archive
        xcodebuild -exportArchive -archivePath ExodusWallet.xcarchive -exportPath . -exportOptionsPlist <(cat << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>compileBitcode</key>
          <false/>
        </dict>
        </plist>
        EOF
        )
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ExodusWallet-IPA
        path: ExodusWallet/*.ipa
